<a href="https://colab.research.google.com/github/Xhandra23/data-anaylsis-/blob/main/datetime.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = pd.DataFrame ({
    "EMPID": [101,102,103,104,105,106,107,108,109,110,110],

    "Name": ["Ravi","PRIYA","Arun","sneha","Kiran","ANJALI",
             "Vikram","meena","RAHUL","Sneha","Sneha"],

    "City": ["Hyderabad","Hyderabad","CHENNAI","Chennai","Bangalore",
             "BANGALORE","Mumbai","mumbai","Delhi","Hyderabad","Hyderabad"],

    "Salary": [30000,40000,3500,4500,32000,50000,
               38000,42000,36000,45000,45000],

    "Age": [25,28,24,26,30,27,32,29,31,23,23]
})

#shalow copy
df=data.copy(deep=True)

df.loc[2,"Salary"] =40000
print(data)
print(df)

    EMPID    Name       City  Salary  Age
0     101    Ravi  Hyderabad   30000   25
1     102   PRIYA  Hyderabad   40000   28
2     103    Arun    CHENNAI    3500   24
3     104   sneha    Chennai    4500   26
4     105   Kiran  Bangalore   32000   30
5     106  ANJALI  BANGALORE   50000   27
6     107  Vikram     Mumbai   38000   32
7     108   meena     mumbai   42000   29
8     109   RAHUL      Delhi   36000   31
9     110   Sneha  Hyderabad   45000   23
10    110   Sneha  Hyderabad   45000   23
    EMPID    Name       City  Salary  Age
0     101    Ravi  Hyderabad   30000   25
1     102   PRIYA  Hyderabad   40000   28
2     103    Arun    CHENNAI   40000   24
3     104   sneha    Chennai    4500   26
4     105   Kiran  Bangalore   32000   30
5     106  ANJALI  BANGALORE   50000   27
6     107  Vikram     Mumbai   38000   32
7     108   meena     mumbai   42000   29
8     109   RAHUL      Delhi   36000   31
9     110   Sneha  Hyderabad   45000   23
10    110   Sneha  Hyderabad   45000   23

In [ ]:
import pandas as pd
data = {
    'Date':["2026-01-01","2026-01-02","2026-01-03","2026-01-04","2026-01-05"],
    "Sales":[5000,6500,4200,7000,5500]
}
df = pd.DataFrame(data)
print(df)
print(df.dtypes)
df["Date"] = pd.to_datetime(df["Date"])
print(df.dtypes)

print(df["Date"])

print(df["Date"].iloc[0:3])

         Date  Sales
0  2026-01-01   5000
1  2026-01-02   6500
2  2026-01-03   4200
3  2026-01-04   7000
4  2026-01-05   5500
Date     object
Sales     int64
dtype: object
Date     datetime64[ns]
Sales             int64
dtype: object
0   2026-01-01
1   2026-01-02
2   2026-01-03
3   2026-01-04
4   2026-01-05
Name: Date, dtype: datetime64[ns]
0   2026-01-01
1   2026-01-02
2   2026-01-03
Name: Date, dtype: datetime64[ns]

In [ ]:
import pandas as pd

data = {
    'Date': [
        "2026-01-01 10:30:15",
        "2026-01-02 11:45:30",
        "2026-01-03 09:15:45",
        "2026-01-04 14:20:10",
        "2026-01-05 16:50:55"
    ],
    "Sales": [5000, 6500, 4200, 7000, 5500]
}

df = pd.DataFrame(data)

df["Date"] = pd.to_datetime(df["Date"])

print(df)
df["Date"].dt.hour
df["Date"].dt.minute
df["Date"].dt.second

                 Date  Sales
0 2026-01-01 10:30:15   5000
1 2026-01-02 11:45:30   6500
2 2026-01-03 09:15:45   4200
3 2026-01-04 14:20:10   7000
4 2026-01-05 16:50:55   5500

0    15
1    30
2    45
3    10
4    55
Name: Date, dtype: int32

In [ ]:
import pandas as pd
dates = pd.date_range(
    start="2026-06-16",
    end="2026-11-23"
)
print(dates)

DatetimeIndex(['2026-06-16', '2026-06-17', '2026-06-18', '2026-06-19',
               '2026-06-20', '2026-06-21', '2026-06-22', '2026-06-23',
               '2026-06-24', '2026-06-25',
               ...
               '2026-11-14', '2026-11-15', '2026-11-16', '2026-11-17',
               '2026-11-18', '2026-11-19', '2026-11-20', '2026-11-21',
               '2026-11-22', '2026-11-23'],
              dtype='datetime64[ns]', length=161, freq='D')

161

In [ ]:
import pandas as pd
dates = pd.date_range(
    start="2026-06-16",
    periods=100
)
print(dates)
len(dates)

DatetimeIndex(['2026-06-16', '2026-06-17', '2026-06-18', '2026-06-19',
               '2026-06-20', '2026-06-21', '2026-06-22', '2026-06-23',
               '2026-06-24', '2026-06-25', '2026-06-26', '2026-06-27',
               '2026-06-28', '2026-06-29', '2026-06-30', '2026-07-01',
               '2026-07-02', '2026-07-03', '2026-07-04', '2026-07-05',
               '2026-07-06', '2026-07-07', '2026-07-08', '2026-07-09',
               '2026-07-10', '2026-07-11', '2026-07-12', '2026-07-13',
               '2026-07-14', '2026-07-15', '2026-07-16', '2026-07-17',
               '2026-07-18', '2026-07-19', '2026-07-20', '2026-07-21',
               '2026-07-22', '2026-07-23', '2026-07-24', '2026-07-25',
               '2026-07-26', '2026-07-27', '2026-07-28', '2026-07-29',
               '2026-07-30', '2026-07-31', '2026-08-01', '2026-08-02',
               '2026-08-03', '2026-08-04', '2026-08-05', '2026-08-06',
               '2026-08-07', '2026-08-08', '2026-08-09', '2026-08-10',
               '2026-08-11', '2026-08-12', '2026-08-13', '2026-08-14',
               '2026-08-15', '2026-08-16', '2026-08-17', '2026-08-18',
               '2026-08-19', '2026-08-20', '2026-08-21', '2026-08-22',
               '2026-08-23', '2026-08-24', '2026-08-25', '2026-08-26',
               '2026-08-27', '2026-08-28', '2026-08-29', '2026-08-30',
               '2026-08-31', '2026-09-01', '2026-09-02', '2026-09-03',
               '2026-09-04', '2026-09-05', '2026-09-06', '2026-09-07',
               '2026-09-08', '2026-09-09', '2026-09-10', '2026-09-11',
               '2026-09-12', '2026-09-13', '2026-09-14', '2026-09-15',
               '2026-09-16', '2026-09-17', '2026-09-18', '2026-09-19',
               '2026-09-20', '2026-09-21', '2026-09-22', '2026-09-23'],
              dtype='datetime64[ns]', freq='D')

100

In [ ]:
date = pd.date_range(start="2026-03-01",periods=30,freq='h')
print(date)

DatetimeIndex(['2026-03-01 00:00:00', '2026-03-01 01:00:00',
               '2026-03-01 02:00:00', '2026-03-01 03:00:00',
               '2026-03-01 04:00:00', '2026-03-01 05:00:00',
               '2026-03-01 06:00:00', '2026-03-01 07:00:00',
               '2026-03-01 08:00:00', '2026-03-01 09:00:00',
               '2026-03-01 10:00:00', '2026-03-01 11:00:00',
               '2026-03-01 12:00:00', '2026-03-01 13:00:00',
               '2026-03-01 14:00:00', '2026-03-01 15:00:00',
               '2026-03-01 16:00:00', '2026-03-01 17:00:00',
               '2026-03-01 18:00:00', '2026-03-01 19:00:00',
               '2026-03-01 20:00:00', '2026-03-01 21:00:00',
               '2026-03-01 22:00:00', '2026-03-01 23:00:00',
               '2026-03-02 00:00:00', '2026-03-02 01:00:00',
               '2026-03-02 02:00:00', '2026-03-02 03:00:00',
               '2026-03-02 04:00:00', '2026-03-02 05:00:00'],
              dtype='datetime64[ns]', freq='h')

In [ ]:
date = pd.date_range(start="2026-03-01",periods=30,freq='min')
print(date)

DatetimeIndex(['2026-03-01 00:00:00', '2026-03-01 00:01:00',
               '2026-03-01 00:02:00', '2026-03-01 00:03:00',
               '2026-03-01 00:04:00', '2026-03-01 00:05:00',
               '2026-03-01 00:06:00', '2026-03-01 00:07:00',
               '2026-03-01 00:08:00', '2026-03-01 00:09:00',
               '2026-03-01 00:10:00', '2026-03-01 00:11:00',
               '2026-03-01 00:12:00', '2026-03-01 00:13:00',
               '2026-03-01 00:14:00', '2026-03-01 00:15:00',
               '2026-03-01 00:16:00', '2026-03-01 00:17:00',
               '2026-03-01 00:18:00', '2026-03-01 00:19:00',
               '2026-03-01 00:20:00', '2026-03-01 00:21:00',
               '2026-03-01 00:22:00', '2026-03-01 00:23:00',
               '2026-03-01 00:24:00', '2026-03-01 00:25:00',
               '2026-03-01 00:26:00', '2026-03-01 00:27:00',
               '2026-03-01 00:28:00', '2026-03-01 00:29:00'],
              dtype='datetime64[ns]', freq='min')

In [ ]:
date = pd.date_range(start="2026-03-01",periods=30,freq='Me')
print(date)

DatetimeIndex(['2026-03-31', '2026-04-30', '2026-05-31', '2026-06-30',
               '2026-07-31', '2026-08-31', '2026-09-30', '2026-10-31',
               '2026-11-30', '2026-12-31', '2027-01-31', '2027-02-28',
               '2027-03-31', '2027-04-30', '2027-05-31', '2027-06-30',
               '2027-07-31', '2027-08-31', '2027-09-30', '2027-10-31',
               '2027-11-30', '2027-12-31', '2028-01-31', '2028-02-29',
               '2028-03-31', '2028-04-30', '2028-05-31', '2028-06-30',
               '2028-07-31', '2028-08-31'],
              dtype='datetime64[ns]', freq='ME')

/tmp/ipykernel_1463/4085166838.py:1: FutureWarning: 'Me' is deprecated and will be removed in a future version, please use 'ME' instead.
  date = pd.date_range(start="2026-03-01",periods=30,freq='Me')

In [ ]:

import pandas as pd
import numpy as np
date = pd.date_range(start="2023-09-23",periods=90,freq='D')
sales = np.random.randint(20000,30000,size=90)
data ={"Date":date,
       "Sales":sales}
df = pd.DataFrame(data)
print(df)

df.dtypes
df["Date"].dt.year
df["year"] =df["Date"].dt.year
print(df)

df.groupby(df["Date"].dt.year)["Sales"].sum()
df.groupby(df["Date"].dt.year)["Sales"].mean()
df.groupby(df["Date"].dt.year)["Sales"].max()
df.groupby(df["Date"].dt.year)["Sales"].sum()

         Date  Sales
0  2023-09-23  28591
1  2023-09-24  21274
2  2023-09-25  24258
3  2023-09-26  25174
4  2023-09-27  29449
..        ...    ...
85 2023-12-17  24979
86 2023-12-18  20465
87 2023-12-19  24965
88 2023-12-20  28739
89 2023-12-21  24969

[90 rows x 2 columns]
         Date  Sales  year
0  2023-09-23  28591  2023
1  2023-09-24  21274  2023
2  2023-09-25  24258  2023
3  2023-09-26  25174  2023
4  2023-09-27  29449  2023
..        ...    ...   ...
85 2023-12-17  24979  2023
86 2023-12-18  20465  2023
87 2023-12-19  24965  2023
88 2023-12-20  28739  2023
89 2023-12-21  24969  2023

[90 rows x 3 columns]

Date
2023    2222582
Name: Sales, dtype: int64

In [ ]:
import pandas as pd
import numpy as np
date = pd.date_range(start="2023-09-23",periods=90,freq='D')
sales = np.random.randint(20000,30000,size=90)
data ={"Date":date,
       "Sales":sales}
df = pd.DataFrame(data)
print(df)

df['Date'].dt.month
df[df["Date"].dt.month == 10]

df['month'] = df['Date'].dt.month_name()

print(df)

         Date  Sales
0  2023-09-23  28787
1  2023-09-24  23889
2  2023-09-25  25099
3  2023-09-26  24574
4  2023-09-27  24315
..        ...    ...
85 2023-12-17  29308
86 2023-12-18  29009
87 2023-12-19  20639
88 2023-12-20  29720
89 2023-12-21  22245

[90 rows x 2 columns]
         Date  Sales      month
0  2023-09-23  28787  September
1  2023-09-24  23889  September
2  2023-09-25  25099  September
3  2023-09-26  24574  September
4  2023-09-27  24315  September
..        ...    ...        ...
85 2023-12-17  29308   December
86 2023-12-18  29009   December
87 2023-12-19  20639   December
88 2023-12-20  29720   December
89 2023-12-21  22245   December

[90 rows x 3 columns]

Empty DataFrame
Columns: [Date, Sales, month]
Index: []

In [ ]:
import pandas as pd
import numpy as np
date = pd.date_range(start="2023-09-23",periods=90,freq='D')
sales = np.random.randint(20000,30000,size=90)
data ={"Date":date,
       "Sales":sales}
df = pd.DataFrame(data)
print(df)

df["Date"].dt.day
df[df["Date"].dt.day == 23]
df["Date"].dt.day_name()

         Date  Sales
0  2023-09-23  29783
1  2023-09-24  24441
2  2023-09-25  29746
3  2023-09-26  29719
4  2023-09-27  20472
..        ...    ...
85 2023-12-17  24142
86 2023-12-18  21447
87 2023-12-19  22024
88 2023-12-20  22960
89 2023-12-21  21870

[90 rows x 2 columns]

0      Saturday
1        Sunday
2        Monday
3       Tuesday
4     Wednesday
        ...
85       Sunday
86       Monday
87      Tuesday
88    Wednesday
89     Thursday
Name: Date, Length: 90, dtype: object

In [ ]:
import pandas as pd
data = {
    "OrderID": [
        1001, 1002, 1003, 1004, 1005,
        1006, 1007, 1008, 1009, 1010,
        1011, 1012, 1013, 1014, 1015
    ],

    "OrderDateTime": [
        "2024-01-05 09:15:20",
        "2024-02-10 14:30:45",
        "2024-03-15 18:20:10",
        "2024-04-20 11:45:30",
        "2024-05-25 20:10:55",
        "2024-06-12 08:35:15",
        "2024-07-18 16:25:40",
        "2024-08-22 19:50:25",
        "2024-09-05 10:20:35",
        "2024-10-14 13:40:50",
        "2024-11-20 17:15:10",
        "2024-12-25 21:30:45",
        "2025-01-10 09:45:20",
        "2025-02-15 15:10:35",
        "2025-03-20 18:55:50"
    ],

    "Product": [
        "Laptop", "Mobile", "Tablet", "Headphones", "Keyboard",
        "Mouse", "Monitor", "Laptop", "Mobile", "Tablet",
        "Headphones", "Laptop", "Keyboard", "Monitor", "Mobile"
    ],

    "Sales": [
        55000, 25000, 30000, 5000, 3500,
        1500, 18000, 60000, 27000, 32000,
        6500, 58000, 4000, 20000, 29000
    ]
}

df = pd.DataFrame(data)

print(df)
df.dtypes
df["OrderDateTime"] = pd.to_datetime(df["OrderDateTime"])
df.dtypes

    OrderID        OrderDateTime     Product  Sales
0      1001  2024-01-05 09:15:20      Laptop  55000
1      1002  2024-02-10 14:30:45      Mobile  25000
2      1003  2024-03-15 18:20:10      Tablet  30000
3      1004  2024-04-20 11:45:30  Headphones   5000
4      1005  2024-05-25 20:10:55    Keyboard   3500
5      1006  2024-06-12 08:35:15       Mouse   1500
6      1007  2024-07-18 16:25:40     Monitor  18000
7      1008  2024-08-22 19:50:25      Laptop  60000
8      1009  2024-09-05 10:20:35      Mobile  27000
9      1010  2024-10-14 13:40:50      Tablet  32000
10     1011  2024-11-20 17:15:10  Headphones   6500
11     1012  2024-12-25 21:30:45      Laptop  58000
12     1013  2025-01-10 09:45:20    Keyboard   4000
13     1014  2025-02-15 15:10:35     Monitor  20000
14     1015  2025-03-20 18:55:50      Mobile  29000

OrderID                   int64
OrderDateTime    datetime64[ns]
Product                  object
Sales                     int64
dtype: object

In [ ]:
import pandas as pd
import numpy as np
data = pd.date_range(start="2020-01-01",periods=90,freq="me")
sales=np.random.randint(40000,70000,size=90)
df = pd.DataFrame({"Date":data,"Sales":sales})
print(df)

         Date  Sales
0  2020-01-31  52570
1  2020-02-29  51290
2  2020-03-31  48994
3  2020-04-30  49034
4  2020-05-31  68677
..        ...    ...
85 2027-02-28  56019
86 2027-03-31  62397
87 2027-04-30  56696
88 2027-05-31  49742
89 2027-06-30  44214

[90 rows x 2 columns]

/tmp/ipykernel_1463/1536259067.py:3: FutureWarning: 'me' is deprecated and will be removed in a future version, please use 'ME' instead.
  data = pd.date_range(start="2020-01-01",periods=90,freq="me")

In [ ]:
import pandas as pd
import numpy as np
data = pd.date_range(start="2024-01-01",periods=366)
sales=np.random.randint(1000,10000,size=366)
df = pd.DataFrame({"Date":data,"Sales":sales})
print(df)

          Date  Sales
0   2024-01-01   4755
1   2024-01-02   6014
2   2024-01-03   3161
3   2024-01-04   1884
4   2024-01-05   1365
..         ...    ...
361 2024-12-27   7839
362 2024-12-28   1381
363 2024-12-29   4269
364 2024-12-30   2436
365 2024-12-31   9703

[366 rows x 2 columns]

In [ ]:
import pandas as pd
import numpy as np
data = pd.date_range(start="2023-01-01",periods=24,freq="me")
sales=np.random.randint(40000,70000,size=24)
df = pd.DataFrame({"Date":data,"Sales":sales})
print(df)

         Date  Sales
0  2023-01-31  68393
1  2023-02-28  51107
2  2023-03-31  59499
3  2023-04-30  41522
4  2023-05-31  66389
5  2023-06-30  46503
6  2023-07-31  62649
7  2023-08-31  40998
8  2023-09-30  46865
9  2023-10-31  63094
10 2023-11-30  55218
11 2023-12-31  64563
12 2024-01-31  67548
13 2024-02-29  46372
14 2024-03-31  47435
15 2024-04-30  59303
16 2024-05-31  66002
17 2024-06-30  42051
18 2024-07-31  58569
19 2024-08-31  66826
20 2024-09-30  50583
21 2024-10-31  55459
22 2024-11-30  44636
23 2024-12-31  66364

/tmp/ipykernel_1463/4071672003.py:3: FutureWarning: 'me' is deprecated and will be removed in a future version, please use 'ME' instead.
  data = pd.date_range(start="2023-01-01",periods=24,freq="me")

In [ ]:
import pandas as pd
import numpy as np
data = pd.date_range(start="2024-01-01",periods=30,freq="d" & )
sales=np.random.randint(40000,70000,size=30)
df = pd.DataFrame({"Date":data,"Sales":sales})
print(df)

                  Date  Sales
0  2024-01-01 00:00:00  66268
1  2024-01-01 01:00:00  48158
2  2024-01-01 02:00:00  61211
3  2024-01-01 03:00:00  44624
4  2024-01-01 04:00:00  59744
5  2024-01-01 05:00:00  67376
6  2024-01-01 06:00:00  66461
7  2024-01-01 07:00:00  63294
8  2024-01-01 08:00:00  42435
9  2024-01-01 09:00:00  42340
10 2024-01-01 10:00:00  44714
11 2024-01-01 11:00:00  62760
12 2024-01-01 12:00:00  66864
13 2024-01-01 13:00:00  48467
14 2024-01-01 14:00:00  62649
15 2024-01-01 15:00:00  44154
16 2024-01-01 16:00:00  56818
17 2024-01-01 17:00:00  59650
18 2024-01-01 18:00:00  41156
19 2024-01-01 19:00:00  50026
20 2024-01-01 20:00:00  57879
21 2024-01-01 21:00:00  44957
22 2024-01-01 22:00:00  53460
23 2024-01-01 23:00:00  54908
24 2024-01-02 00:00:00  57269
25 2024-01-02 01:00:00  57236
26 2024-01-02 02:00:00  65064
27 2024-01-02 03:00:00  53603
28 2024-01-02 04:00:00  58402
29 2024-01-02 05:00:00  65883