<a href="https://colab.research.google.com/github/Xhandra23/data-anaylsis-/blob/main/series_day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
''' viewing series'''

import pandas as pd

items = pd.Series([
    "Laptop",
    "Mouse",
    "Keyboard",
    "Monitor",
    "Printer",
    "Scanner",
    "Headphones",
    "Webcam",
    "Speaker",
    "USB Cable",
    "Mobile",
    "Tablet",
    "Charger",
    "Power Bank",
    "Hard Disk",
    "Pen Drive",
    "Router",
    "Microphone",
    "Smart Watch",
    "Camera"
])

print(items)

items.head(2)
items.tail(2)
items.shape
len(items)
items.index
items.values

''' filtering'''
items[5:7]
items[[2,4,5]]
items.iloc[4:8]

4       Printer
5       Scanner
6    Headphones
7        Webcam
dtype: object

In [24]:
import pandas as pd

sales = pd.Series(
    [5000, 6500, 4200, 7800, 5500, 9000, 7200],
    index=["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
)

print(sales)

sales > 3000''' it gives only bool value ''''
sales[sales > 3000]''' it gives only actual values in data'''

Monday       5000
Tuesday      6500
Wednesday    4200
Thursday     7800
Friday       5500
Saturday     9000
Sunday       7200
dtype: int64

Monday       5000
Tuesday      6500
Wednesday    4200
Thursday     7800
Friday       5500
Saturday     9000
Sunday       7200
dtype: int64

In [42]:
''' FINDING MISSING VALUES WE (" ISNA AND ISNULL")'''
import pandas as pd

sales = pd.Series(
    [5000, 6500, None, 7800, 5500, None, 7200],
    index=[
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday"
    ]
)

'''print(sales)
sales.isna()
sales.isnull()
print(sales.isnull().sum())
sales.dropna()
sales =sales.dropna()
print(sales)
sales.fillna(5)'''
sales.fillna(sales.mean())

Monday       5000.0
Tuesday      6500.0
Wednesday    6400.0
Thursday     7800.0
Friday       5500.0
Saturday     6400.0
Sunday       7200.0
dtype: float64

In [60]:
 import pandas as pd

weather = pd.Series(
    [25, 23, None, 30, 40, None, None, 36, 32, 20, None, 10],
    index=[
        "January", "February", "March", "April",
        "May", "June", "July", "August",
        "September", "October", "November", "December"
    ],
    name="Weather 2025"
)


''' vewing'''
weather.head()
weather.tail()

weather.shape
weather.index
len(weather)
weather.values
''' filtering'''
print(weather[[2,3,7,5]])
weather[weather > 10]

'''finding missing values'''
weather.isna()
print(weather.isnull().sum())
weather.dropna()
weather.fillna(0)
weather.fillna(weather.mean())

March      NaN
April     30.0
August    36.0
June       NaN
Name: Weather 2025, dtype: float64
4

/tmp/ipykernel_1721/551688425.py:23: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(weather[[2,3,7,5]])

January      25.0
February     23.0
March        27.0
April        30.0
May          40.0
June         27.0
July         27.0
August       36.0
September    32.0
October      20.0
November     27.0
December     10.0
Name: Weather 2025, dtype: float64

In [71]:
''' aggregation functions'''
''' mean()
median()
sum()
min()
max()
std()
'''
import pandas as pd

sales = pd.Series(
    [5000, 6500, 4200, 7800, 5500, 9000, 7200, 6800, 8100, 4500],
    index=[
        "Monday", "Tuesday", "Wednesday", "Thursday", "Friday",
        "Saturday", "Sunday", "Week2-Mon", "Week2-Tue", "Week2-Wed"
    ]
)

print(sales)
print(sales.mean())
print(sales.median())
print(sales.sum())
print(sales.min())
print(sales.max())
print(sales.std())

Monday       5000
Tuesday      6500
Wednesday    4200
Thursday     7800
Friday       5500
Saturday     9000
Sunday       7200
Week2-Mon    6800
Week2-Tue    8100
Week2-Wed    4500
dtype: int64
6460.0
6650.0
64600
4200
9000
1619.4649322126943

In [76]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([6,7,8,9,10])
d=pd.concat([s1,s2],ignore_index=True)
print(d)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64